-- =============================================================================
-- Orders, checkout drafts, stripe idempotency, token RLS
-- Generated by: npm run db:bootstrap:assemble
-- Do not edit by hand — change scripts/db-bootstrap-manifest.ts and re-assemble.
-- =============================================================================
-- Source migrations:
--   supabase/migrations/20250314000000_orders_schema_full.sql
--   supabase/migrations/20250218000000_add_order_cost_columns.sql
--   supabase/migrations/20250220000000_orders_supabase_primary.sql
--   supabase/migrations/20250228100000_orders_performance_indexes.sql
--   supabase/migrations/20250313000000_ga4_purchase_columns.sql
--   supabase/migrations/20250313200000_order_notification_sent.sql
--   supabase/migrations/20250315000000_orders_payment_status_check.sql
--   supabase/migrations/20250326120000_orders_submission_token.sql
--   supabase/migrations/20260410120000_checkout_drafts.sql
--   supabase/migrations/20260416120000_orders_delivered_email_sent_at.sql
--   supabase/migrations/20260419120000_orders_admin_list_sort.sql
--   supabase/migrations/20260420120000_orders_payment_failed_email_sent_at.sql
--   supabase/migrations/20260420133000_orders_rls_token_access.sql
--   supabase/migrations/20260506120000_orders_phone_country_codes.sql
--   supabase/migrations/20260508120000_orders_delivery_destination_zone_postal.sql
--   supabase/migrations/20260511153000_expand_order_status_lifecycle.sql
--   supabase/migrations/20260520130000_orders_marketing_email_consent.sql
-- =============================================================================

-- >>> BEGIN 20250314000000_orders_schema_full.sql

-- Orders schema: single source of truth for Lanna Bloom.
-- Run in Supabase Dashboard → SQL Editor, or via: supabase db push
-- Idempotent: safe to run multiple times (CREATE IF NOT EXISTS, ADD COLUMN IF NOT EXISTS).
--
-- If you already have order_items without an "id" column, create it first or skip the
-- CREATE TABLE order_items block and add columns with ALTER only.

-- =============================================================================
-- 1. ORDERS table
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.orders (
  order_id text PRIMARY KEY,
  public_token text,
  payment_method text,
  customer_name text,
  customer_email text,
  phone text,
  address text,
  district text,
  delivery_window text,
  delivery_date text,
  order_status text DEFAULT 'NEW',
  payment_status text DEFAULT 'NOT_PAID',
  stripe_session_id text,
  stripe_payment_intent_id text,
  paid_at timestamptz,
  items_total numeric(12,2),
  delivery_fee numeric(12,2),
  grand_total numeric(12,2),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  recipient_name text,
  recipient_phone text,
  contact_preference text,
  referral_code text,
  referral_discount numeric(12,2) DEFAULT 0,
  fulfillment_status text DEFAULT 'new',
  fulfillment_status_updated_at timestamptz DEFAULT now(),
  order_json jsonb,
  ga_client_id text,
  admin_notified boolean DEFAULT false,
  admin_notified_at timestamptz
);

-- Add any columns that might be missing (e.g. if table was created before these existed)
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS order_json jsonb;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS fulfillment_status text DEFAULT 'new';
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS fulfillment_status_updated_at timestamptz DEFAULT now();
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS payment_method text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS customer_email text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS ga_client_id text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS admin_notified boolean DEFAULT false;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS admin_notified_at timestamptz;

-- =============================================================================
-- 2. ORDER_ITEMS table
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.order_items (
  id bigserial PRIMARY KEY,
  order_id text NOT NULL REFERENCES public.orders(order_id) ON DELETE CASCADE,
  bouquet_id text,
  bouquet_title text,
  size text,
  price numeric(12,2),
  image_url_snapshot text,
  item_type text DEFAULT 'bouquet',
  cost numeric(12,2),
  commission_amount numeric(12,2)
);

CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON public.order_items(order_id);

ALTER TABLE public.order_items ADD COLUMN IF NOT EXISTS item_type text DEFAULT 'bouquet';
ALTER TABLE public.order_items ADD COLUMN IF NOT EXISTS cost numeric(12,2);
ALTER TABLE public.order_items ADD COLUMN IF NOT EXISTS commission_amount numeric(12,2);

-- =============================================================================
-- 3. ORDER_STATUS_HISTORY table
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.order_status_history (
  id bigserial PRIMARY KEY,
  order_id text NOT NULL REFERENCES public.orders(order_id) ON DELETE CASCADE,
  from_status text,
  to_status text,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_order_status_history_order_id ON public.order_status_history(order_id);

-- =============================================================================
-- 4. Indexes (if not already present from other migrations)
-- =============================================================================
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON public.orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_order_status ON public.orders(order_status);
CREATE INDEX IF NOT EXISTS idx_orders_payment_status ON public.orders(payment_status);
CREATE INDEX IF NOT EXISTS idx_orders_district ON public.orders(district);
CREATE INDEX IF NOT EXISTS idx_orders_delivery_date ON public.orders(delivery_date);

-- <<< END 20250314000000_orders_schema_full.sql

-- >>> BEGIN 20250218000000_add_order_cost_columns.sql

-- Add cost and profit columns + customer_email to orders table
-- Run in Supabase SQL Editor if columns don't exist

ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS customer_email text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS cogs_amount numeric(12,2);
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS delivery_cost numeric(12,2);
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS payment_fee numeric(12,2);
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS total_amount numeric(12,2);
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

-- Backfill total_amount from grand_total for existing rows (optional)
UPDATE public.orders
SET total_amount = grand_total
WHERE total_amount IS NULL AND grand_total IS NOT NULL;

-- <<< END 20250218000000_add_order_cost_columns.sql

-- >>> BEGIN 20250220000000_orders_supabase_primary.sql

-- Add columns for Supabase-as-primary order storage and fulfillment status
-- Run in Supabase SQL Editor

-- order_json: full order payload for migration/backfill and fast reads
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS order_json jsonb;

-- Fulfillment status (customer-facing): new, confirmed, preparing, dispatched, delivered, cancelled, issue
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS fulfillment_status text DEFAULT 'new';
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS fulfillment_status_updated_at timestamptz DEFAULT now();

-- Backfill fulfillment_status for existing rows
UPDATE public.orders
SET fulfillment_status = 'new'
WHERE fulfillment_status IS NULL;

-- Stripe webhook idempotency: prevent double-processing
CREATE TABLE IF NOT EXISTS public.stripe_events (
  event_id text PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  type text
);

CREATE INDEX IF NOT EXISTS idx_stripe_events_created_at ON public.stripe_events(created_at DESC);

-- <<< END 20250220000000_orders_supabase_primary.sql

-- >>> BEGIN 20250228100000_orders_performance_indexes.sql

-- Performance indexes for orders table
-- Speeds up admin filters, order lookup, and list sorting

-- Sort by created_at (most common)
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON public.orders(created_at DESC);

-- Filter by status
CREATE INDEX IF NOT EXISTS idx_orders_order_status ON public.orders(order_status);
CREATE INDEX IF NOT EXISTS idx_orders_payment_status ON public.orders(payment_status);

-- Filter by district and delivery date
CREATE INDEX IF NOT EXISTS idx_orders_district ON public.orders(district);
CREATE INDEX IF NOT EXISTS idx_orders_delivery_date ON public.orders(delivery_date);

-- order_items and order_status_history: foreign key lookups
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON public.order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_status_history_order_id ON public.order_status_history(order_id);

-- Enable pg_trgm for ilike search on order_id, phone, recipient_phone
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- GIN indexes for ilike('%...%') on text columns
CREATE INDEX IF NOT EXISTS idx_orders_order_id_trgm ON public.orders USING gin(order_id gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_orders_phone_trgm ON public.orders USING gin(phone gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_orders_recipient_phone_trgm ON public.orders USING gin(recipient_phone gin_trgm_ops);

-- <<< END 20250228100000_orders_performance_indexes.sql

-- >>> BEGIN 20250313000000_ga4_purchase_columns.sql

-- GA4 Measurement Protocol: idempotency and optional client id for purchase events
-- Run in Supabase SQL Editor

ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS ga4_purchase_sent boolean DEFAULT false;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS ga4_purchase_sent_at timestamptz;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS ga_client_id text;

COMMENT ON COLUMN public.orders.ga4_purchase_sent IS 'True after backend sent GA4 purchase via Measurement Protocol (prevents duplicate sends)';
COMMENT ON COLUMN public.orders.ga4_purchase_sent_at IS 'Timestamp when GA4 purchase was sent';
COMMENT ON COLUMN public.orders.ga_client_id IS 'Optional GA client_id from frontend for server-side purchase attribution';

-- <<< END 20250313000000_ga4_purchase_columns.sql

-- >>> BEGIN 20250313200000_order_notification_sent.sql

-- Idempotency for admin "new order" notifications: one email per order.
CREATE TABLE IF NOT EXISTS public.order_notification_sent (
  order_id text NOT NULL,
  notification_type text NOT NULL,
  created_at timestamptz DEFAULT now(),
  PRIMARY KEY (order_id, notification_type)
);

CREATE INDEX IF NOT EXISTS idx_order_notification_sent_created_at
  ON public.order_notification_sent(created_at DESC);

COMMENT ON TABLE public.order_notification_sent IS 'Tracks sent notifications per order to prevent duplicate emails (e.g. admin_new_order).';

-- <<< END 20250313200000_order_notification_sent.sql

-- >>> BEGIN 20250315000000_orders_payment_status_check.sql

-- Fix orders_payment_status_check so it allows the values the app sends.
-- App uses: NOT_PAID (new/pending), PAID, ERROR, CANCELLED.

ALTER TABLE public.orders
  DROP CONSTRAINT IF EXISTS orders_payment_status_check;

ALTER TABLE public.orders
  ADD CONSTRAINT orders_payment_status_check
  CHECK (payment_status IN ('NOT_PAID', 'PAID', 'CANCELLED', 'ERROR'));

-- <<< END 20250315000000_orders_payment_status_check.sql

-- >>> BEGIN 20250326120000_orders_submission_token.sql

-- Idempotent checkout: one order per submission token (browser-generated UUID).
-- Safe to run multiple times.

ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS submission_token text;

CREATE UNIQUE INDEX IF NOT EXISTS idx_orders_submission_token_unique
  ON public.orders (submission_token)
  WHERE submission_token IS NOT NULL;

-- <<< END 20250326120000_orders_submission_token.sql

-- >>> BEGIN 20260410120000_checkout_drafts.sql

-- Pending checkout payloads: order is created only after Stripe payment succeeds.
create table if not exists public.checkout_drafts (
  id uuid primary key default gen_random_uuid(),
  submission_token text not null unique,
  payload_json jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_checkout_drafts_updated_at on public.checkout_drafts(updated_at desc);

-- <<< END 20260410120000_checkout_drafts.sql

-- >>> BEGIN 20260416120000_orders_delivered_email_sent_at.sql

-- One post-delivery customer email per order (idempotent via delivered_email_sent_at).

ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS delivered_email_sent_at timestamptz;

COMMENT ON COLUMN public.orders.delivered_email_sent_at IS
  'Set when the post-delivery thank-you/review email was successfully claimed for sending; null means not sent yet.';

-- <<< END 20260416120000_orders_delivered_email_sent_at.sql

-- >>> BEGIN 20260419120000_orders_admin_list_sort.sql

-- Admin order list: sort pending deliveries first, then by delivery_date (see getOrders / getOrdersForExport).

ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS admin_needs_delivery_sort smallint
  GENERATED ALWAYS AS (
    CASE
      WHEN order_status IS NULL THEN 1
      WHEN upper(trim(order_status::text)) IN ('DELIVERED', 'CANCELLED') THEN 0
      ELSE 1
    END
  ) STORED;

COMMENT ON COLUMN public.orders.admin_needs_delivery_sort IS
  '1 = still in delivery pipeline; 0 = terminal (delivered/cancelled). Used for admin list ordering.';

CREATE INDEX IF NOT EXISTS idx_orders_admin_needs_delivery_sort
  ON public.orders (admin_needs_delivery_sort DESC, delivery_date ASC NULLS LAST, created_at DESC);

-- <<< END 20260419120000_orders_admin_list_sort.sql

-- >>> BEGIN 20260420120000_orders_payment_failed_email_sent_at.sql

-- One payment-failed customer email per order (idempotent via payment_failed_email_sent_at).

ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS payment_failed_email_sent_at timestamptz;

COMMENT ON COLUMN public.orders.payment_failed_email_sent_at IS
  'Set when the Stripe payment-failed customer email was successfully claimed for sending; null means not sent yet. Cleared if the send fails so a later retry can claim again.';

-- <<< END 20260420120000_orders_payment_failed_email_sent_at.sql

-- >>> BEGIN 20260420133000_orders_rls_token_access.sql

-- Harden sensitive data exposure with row-level security.
-- Customer self-service reads are allowed only when request carries matching x-order-token.
-- Backend service-role access continues to work (service role bypasses RLS).

-- -----------------------------------------------------------------------------
-- Helper: read order token from request headers (PostgREST/Supabase context)
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.request_order_token()
RETURNS text
LANGUAGE sql
STABLE
AS $$
  SELECT NULLIF(
    BTRIM(COALESCE((current_setting('request.headers', true)::jsonb ->> 'x-order-token'), '')),
    ''
  );
$$;

COMMENT ON FUNCTION public.request_order_token() IS
  'Returns x-order-token from request headers for token-scoped customer read policies.';

-- -----------------------------------------------------------------------------
-- Primary customer-sensitive order tables: enable RLS + token-scoped read policies
-- -----------------------------------------------------------------------------
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_status_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "orders_token_scoped_read" ON public.orders;
CREATE POLICY "orders_token_scoped_read"
  ON public.orders
  FOR SELECT
  TO anon, authenticated
  USING (
    public_token IS NOT NULL
    AND public_token = public.request_order_token()
  );

DROP POLICY IF EXISTS "order_items_token_scoped_read" ON public.order_items;
CREATE POLICY "order_items_token_scoped_read"
  ON public.order_items
  FOR SELECT
  TO anon, authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.orders o
      WHERE o.order_id = order_items.order_id
        AND o.public_token IS NOT NULL
        AND o.public_token = public.request_order_token()
    )
  );

DROP POLICY IF EXISTS "order_status_history_token_scoped_read" ON public.order_status_history;
CREATE POLICY "order_status_history_token_scoped_read"
  ON public.order_status_history
  FOR SELECT
  TO anon, authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.orders o
      WHERE o.order_id = order_status_history.order_id
        AND o.public_token IS NOT NULL
        AND o.public_token = public.request_order_token()
    )
  );

-- -----------------------------------------------------------------------------
-- Adjacent sensitive/operational tables: enable RLS with no anon/auth policies.
-- This keeps them private unless accessed by service-role trusted backend.
-- -----------------------------------------------------------------------------
ALTER TABLE IF EXISTS public.admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.stripe_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.line_order_drafts ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.line_integration_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.line_agent_payment_notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.order_notification_sent ENABLE ROW LEVEL SECURITY;

-- <<< END 20260420133000_orders_rls_token_access.sql

-- >>> BEGIN 20260506120000_orders_phone_country_codes.sql

-- Calling codes the customer selected at checkout (digits only, e.g. 66, 1, 44).
-- Used for admin display; full E.164-style number remains in phone / recipient_phone.

alter table public.orders
  add column if not exists phone_country_code text,
  add column if not exists recipient_phone_country_code text;

comment on column public.orders.phone_country_code is 'Customer phone ITU calling code digits from checkout (e.g. 66)';
comment on column public.orders.recipient_phone_country_code is 'Recipient phone ITU calling code digits when ordering for someone else';

-- <<< END 20260506120000_orders_phone_country_codes.sql

-- >>> BEGIN 20260508120000_orders_delivery_destination_zone_postal.sql

-- Province expansion: canonical delivery geography + inferred postcode (storage only; fee uses destination + zone).

alter table public.orders
  add column if not exists delivery_destination text,
  add column if not exists delivery_zone text,
  add column if not exists postal_code text;

create index if not exists orders_delivery_destination_idx
  on public.orders (delivery_destination)
  where delivery_destination is not null;

comment on column public.orders.delivery_destination is 'Canonical market id e.g. CHIANG_MAI, PHUKET';
comment on column public.orders.delivery_zone is 'Stable zone id from lib/delivery/zones.ts';
comment on column public.orders.postal_code is '5-digit Thai postcode inferred server-side when possible';

-- <<< END 20260508120000_orders_delivery_destination_zone_postal.sql

-- >>> BEGIN 20260511153000_expand_order_status_lifecycle.sql

-- Align order_status with the customer-facing lifecycle.
-- Payment confirmation remains in payment_status; order_status is the admin-controlled fulfillment pipeline.

ALTER TABLE public.orders
  DROP CONSTRAINT IF EXISTS orders_order_status_check;

UPDATE public.orders
SET order_status = CASE
  WHEN order_status IS NULL OR trim(order_status::text) = '' THEN 'NEW'
  WHEN upper(trim(order_status::text)) = 'PAID' THEN 'NEW'
  WHEN upper(trim(order_status::text)) IN ('ACCEPTED', 'ORDER_ACCEPTED') THEN 'ACCEPTED'
  WHEN upper(trim(order_status::text)) IN ('PROCESSING', 'PREPARING') THEN 'PREPARING'
  WHEN upper(trim(order_status::text)) IN ('READY_TO_DISPATCH', 'READY_FOR_DISPATCH', 'READY_FOR_DELIVERY') THEN 'READY_FOR_DELIVERY'
  WHEN upper(trim(order_status::text)) IN ('DISPATCHED', 'OUT_FOR_DELIVERY') THEN 'OUT_FOR_DELIVERY'
  WHEN upper(trim(order_status::text)) = 'DELIVERED' THEN 'DELIVERED'
  WHEN upper(trim(order_status::text)) IN ('CANCELED', 'CANCELLED', 'REFUNDED') THEN 'CANCELLED'
  ELSE 'NEW'
END
WHERE order_status IS DISTINCT FROM CASE
  WHEN order_status IS NULL OR trim(order_status::text) = '' THEN 'NEW'
  WHEN upper(trim(order_status::text)) = 'PAID' THEN 'NEW'
  WHEN upper(trim(order_status::text)) IN ('ACCEPTED', 'ORDER_ACCEPTED') THEN 'ACCEPTED'
  WHEN upper(trim(order_status::text)) IN ('PROCESSING', 'PREPARING') THEN 'PREPARING'
  WHEN upper(trim(order_status::text)) IN ('READY_TO_DISPATCH', 'READY_FOR_DISPATCH', 'READY_FOR_DELIVERY') THEN 'READY_FOR_DELIVERY'
  WHEN upper(trim(order_status::text)) IN ('DISPATCHED', 'OUT_FOR_DELIVERY') THEN 'OUT_FOR_DELIVERY'
  WHEN upper(trim(order_status::text)) = 'DELIVERED' THEN 'DELIVERED'
  WHEN upper(trim(order_status::text)) IN ('CANCELED', 'CANCELLED', 'REFUNDED') THEN 'CANCELLED'
  ELSE 'NEW'
END;

ALTER TABLE public.orders
  ALTER COLUMN order_status SET DEFAULT 'NEW';

ALTER TABLE public.orders
  ADD CONSTRAINT orders_order_status_check
  CHECK (order_status IN (
    'NEW',
    'ACCEPTED',
    'PREPARING',
    'READY_FOR_DELIVERY',
    'OUT_FOR_DELIVERY',
    'DELIVERED',
    'CANCELLED'
  ));

-- <<< END 20260511153000_expand_order_status_lifecycle.sql

-- >>> BEGIN 20260520130000_orders_marketing_email_consent.sql

-- Optional checkout consent for promotional email and Trustpilot review invitations (BCC).

ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS marketing_email_consent boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN public.orders.marketing_email_consent IS
  'Customer opted in at checkout to offers and review-invitation email (e.g. Trustpilot BCC on delivered email).';

-- <<< END 20260520130000_orders_marketing_email_consent.sql

