-- =============================================================================
-- Admin users, partner applications, reviews, newsletter
-- Generated by: npm run db:bootstrap:assemble
-- Do not edit by hand — change scripts/db-bootstrap-manifest.ts and re-assemble.
-- =============================================================================
-- Source migrations:
--   supabase/migrations/20250218100000_admin_users_audit_logs.sql
--   supabase/migrations/20250227000000_partner_applications.sql
--   supabase/migrations/20250227100000_partner_temp_password.sql
--   supabase/migrations/20250301000000_customer_reviews.sql
--   supabase/migrations/20250302000000_customer_reviews_rating.sql
--   supabase/migrations/20250308000000_newsletter_subscribers.sql
--   supabase/migrations/20260506130000_welcome_codes.sql
--   supabase/migrations/20260508140500_reviews_admin_only.sql
-- =============================================================================

-- >>> BEGIN 20250218100000_admin_users_audit_logs.sql

-- admin_users
CREATE TABLE IF NOT EXISTS public.admin_users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text UNIQUE NOT NULL,
  name text,
  password_hash text NOT NULL,
  role text NOT NULL CHECK (role IN ('OWNER','MANAGER','SUPPORT')),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_admin_users_email ON public.admin_users(email);

-- updated_at trigger for admin_users
CREATE OR REPLACE FUNCTION update_admin_users_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS admin_users_updated_at ON public.admin_users;
CREATE TRIGGER admin_users_updated_at
  BEFORE UPDATE ON public.admin_users
  FOR EACH ROW EXECUTE FUNCTION update_admin_users_updated_at();

-- audit_logs
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_email text NOT NULL,
  action text NOT NULL,
  target_order_id text,
  diff_json jsonb,
  created_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON public.audit_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_target_order_id ON public.audit_logs(target_order_id);

-- <<< END 20250218100000_admin_users_audit_logs.sql

-- >>> BEGIN 20250227000000_partner_applications.sql

-- Partner applications table (Supabase only; no partner_products)
-- Applications workflow; partner auth; Sanity holds partners + products

CREATE TABLE IF NOT EXISTS public.partner_applications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz DEFAULT now(),
  -- Contact
  shop_name text NOT NULL,
  contact_name text NOT NULL,
  email text NOT NULL,
  line_id text,
  phone text NOT NULL,
  instagram text,
  facebook text,
  -- Location
  address text,
  district text,
  lat numeric,
  lng numeric,
  -- Delivery
  self_deliver boolean DEFAULT false,
  delivery_zones text,
  delivery_fee_note text,
  -- Capacity
  categories text[],
  prep_time text,
  cutoff_time text,
  max_orders_per_day int,
  -- Portfolio
  sample_photo_urls text[],
  experience_note text,
  -- Status & admin
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'needs_changes', 'draft')),
  admin_note text,
  user_id uuid REFERENCES auth.users(id),
  sanity_partner_id text
);

CREATE INDEX IF NOT EXISTS idx_partner_applications_status ON public.partner_applications(status);
CREATE INDEX IF NOT EXISTS idx_partner_applications_user_id ON public.partner_applications(user_id);
CREATE INDEX IF NOT EXISTS idx_partner_applications_created_at ON public.partner_applications(created_at DESC);

-- RLS: public can insert (apply); admin uses service role for read/update
ALTER TABLE public.partner_applications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public insert" ON public.partner_applications
  FOR INSERT TO anon, authenticated WITH CHECK (true);

-- Admin reads/updates via service role (bypasses RLS) or add policy for admin role if needed

-- <<< END 20250227000000_partner_applications.sql

-- >>> BEGIN 20250227100000_partner_temp_password.sql

-- Store temp password for approved partners (admin-only, for password recovery)
ALTER TABLE public.partner_applications
ADD COLUMN IF NOT EXISTS temp_password text;

-- <<< END 20250227100000_partner_temp_password.sql

-- >>> BEGIN 20250301000000_customer_reviews.sql

-- Customer reviews: name + comment, no verification required.
-- Shareable link for customers to leave feedback.

CREATE TABLE IF NOT EXISTS public.customer_reviews (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz DEFAULT now(),
  name text NOT NULL,
  comment text NOT NULL,
  status text NOT NULL DEFAULT 'approved' CHECK (status IN ('pending', 'approved', 'hidden'))
);

CREATE INDEX IF NOT EXISTS idx_customer_reviews_created_at ON public.customer_reviews(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_customer_reviews_status ON public.customer_reviews(status);

-- RLS: allow anyone to insert (no auth); allow public read of approved only
ALTER TABLE public.customer_reviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public insert" ON public.customer_reviews
  FOR INSERT TO anon, authenticated WITH CHECK (true);

CREATE POLICY "Allow public read approved" ON public.customer_reviews
  FOR SELECT TO anon, authenticated USING (status = 'approved');

-- Admin reads/updates via service role (bypasses RLS)

-- <<< END 20250301000000_customer_reviews.sql

-- >>> BEGIN 20250302000000_customer_reviews_rating.sql

-- Add rating and review_date to customer_reviews for admin-pasted Google reviews
ALTER TABLE public.customer_reviews
  ADD COLUMN IF NOT EXISTS rating integer,
  ADD COLUMN IF NOT EXISTS review_date date;

-- Constraint: rating 1-5 when set
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'customer_reviews_rating_check'
  ) THEN
    ALTER TABLE public.customer_reviews
      ADD CONSTRAINT customer_reviews_rating_check
      CHECK (rating IS NULL OR (rating >= 1 AND rating <= 5));
  END IF;
END $$;

-- Default existing rows to 5 stars
UPDATE public.customer_reviews SET rating = 5 WHERE rating IS NULL;

COMMENT ON COLUMN public.customer_reviews.rating IS '1-5 stars, from Google or manual';
COMMENT ON COLUMN public.customer_reviews.review_date IS 'Original review date when pasted from Google';

-- <<< END 20250302000000_customer_reviews_rating.sql

-- >>> BEGIN 20250308000000_newsletter_subscribers.sql

-- Newsletter subscribers table. Stores emails from footer signup and other sources.
-- Used for MVP: store emails in Supabase and notify business via Resend.

CREATE TABLE IF NOT EXISTS public.newsletter_subscribers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Email stored in lowercase for case-insensitive uniqueness
  email text NOT NULL,
  -- Source of signup (e.g. 'footer', 'popup', 'checkout')
  source text NOT NULL DEFAULT 'footer',
  -- Status: active, unsubscribed, etc.
  status text NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT newsletter_subscribers_email_unique UNIQUE (email)
);

-- Ensure email is lowercase on insert/update
CREATE OR REPLACE FUNCTION newsletter_subscribers_lowercase_email()
RETURNS TRIGGER AS $$
BEGIN
  NEW.email := lower(trim(NEW.email));
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER newsletter_subscribers_lowercase_email_trigger
  BEFORE INSERT OR UPDATE ON public.newsletter_subscribers
  FOR EACH ROW
  EXECUTE FUNCTION newsletter_subscribers_lowercase_email();

CREATE INDEX IF NOT EXISTS idx_newsletter_subscribers_email ON public.newsletter_subscribers(email);
CREATE INDEX IF NOT EXISTS idx_newsletter_subscribers_created_at ON public.newsletter_subscribers(created_at DESC);

-- RLS: public can insert (signup); admin uses service role for reads
ALTER TABLE public.newsletter_subscribers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public insert" ON public.newsletter_subscribers
  FOR INSERT TO anon, authenticated WITH CHECK (true);

-- Admin reads via service role (bypasses RLS)

COMMENT ON TABLE public.newsletter_subscribers IS 'Newsletter signup emails from footer and other sources';
COMMENT ON COLUMN public.newsletter_subscribers.email IS 'Subscriber email, stored lowercase';
COMMENT ON COLUMN public.newsletter_subscribers.source IS 'Signup source (footer, popup, etc.)';
COMMENT ON COLUMN public.newsletter_subscribers.status IS 'active, unsubscribed, etc.';

-- <<< END 20250308000000_newsletter_subscribers.sql

-- >>> BEGIN 20260506130000_welcome_codes.sql

-- Welcome codes for newsletter subscribers (unique, single-use promo codes).
-- Stored in Supabase so the server can validate + redeem codes securely.

CREATE TABLE IF NOT EXISTS public.welcome_codes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Full code string, e.g. 'WELCOME10-7K4D2P'
  code text NOT NULL,
  -- Subscriber email (stored lowercase for consistency)
  email text NOT NULL,
  discount_type text NOT NULL DEFAULT 'percent',
  discount_value int NOT NULL DEFAULT 10,
  created_at timestamptz NOT NULL DEFAULT now(),
  -- Expiry window for welcome promo codes.
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '7 days'),
  redeemed_at timestamptz,
  redeemed_order_id text,
  CONSTRAINT welcome_codes_code_unique UNIQUE (code),
  CONSTRAINT welcome_codes_discount_type_check CHECK (discount_type IN ('percent', 'fixed', 'free_delivery')),
  CONSTRAINT welcome_codes_discount_value_check CHECK (discount_value >= 0)
);

-- Ensure email is lowercase on insert/update
CREATE OR REPLACE FUNCTION welcome_codes_lowercase_email()
RETURNS TRIGGER AS $$
BEGIN
  NEW.email := lower(trim(NEW.email));
  NEW.code := upper(trim(NEW.code));
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS welcome_codes_lowercase_email_trigger ON public.welcome_codes;
CREATE TRIGGER welcome_codes_lowercase_email_trigger
  BEFORE INSERT OR UPDATE ON public.welcome_codes
  FOR EACH ROW
  EXECUTE FUNCTION welcome_codes_lowercase_email();

CREATE INDEX IF NOT EXISTS idx_welcome_codes_code ON public.welcome_codes(code);
CREATE INDEX IF NOT EXISTS idx_welcome_codes_email ON public.welcome_codes(email);
CREATE INDEX IF NOT EXISTS idx_welcome_codes_created_at ON public.welcome_codes(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_welcome_codes_redeemed_at ON public.welcome_codes(redeemed_at);
CREATE INDEX IF NOT EXISTS idx_welcome_codes_expires_at ON public.welcome_codes(expires_at);

-- RLS: service role only (no public policies)
ALTER TABLE public.welcome_codes ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.welcome_codes IS 'Unique welcome promo codes for newsletter subscribers; validated server-side and single-use via redeemed_at.';
COMMENT ON COLUMN public.welcome_codes.code IS 'Unique promo code (uppercase).';
COMMENT ON COLUMN public.welcome_codes.email IS 'Subscriber email (lowercase).';
COMMENT ON COLUMN public.welcome_codes.discount_type IS 'percent, fixed, free_delivery.';
COMMENT ON COLUMN public.welcome_codes.discount_value IS 'Percent or fixed amount (type-dependent).';
COMMENT ON COLUMN public.welcome_codes.redeemed_at IS 'Set when code is redeemed on a paid order.';

-- <<< END 20260506130000_welcome_codes.sql

-- >>> BEGIN 20260508140500_reviews_admin_only.sql

-- Reviews: admin/staff only. No public inserts.
-- Customers should leave reviews on Google; the site can display approved reviews.

-- Remove public insert policy entirely (RLS remains enabled).
DROP POLICY IF EXISTS "Allow public insert" ON public.customer_reviews;

-- Keep admin defaults consistent for dashboard inserts.
ALTER TABLE public.customer_reviews
  ALTER COLUMN status SET DEFAULT 'approved';

-- <<< END 20260508140500_reviews_admin_only.sql

