-- =============================================================================
-- Expenses, income, transfers, withdrawals, storage buckets
-- Generated by: npm run db:bootstrap:assemble
-- Do not edit by hand — change scripts/db-bootstrap-manifest.ts and re-assemble.
-- =============================================================================
-- Source migrations:
--   supabase/migrations/20260406000000_expenses.sql
--   supabase/migrations/20260406010000_income_records.sql
--   supabase/migrations/20260406120000_income_processing_fee.sql
--   supabase/migrations/20260408001000_accounting_transfers.sql
--   supabase/migrations/20260414120000_expense_receipt_images.sql
--   supabase/migrations/20260430130000_accounting_transfer_payout_metadata.sql
--   supabase/migrations/20260502120000_income_paid_date.sql
--   supabase/migrations/20260503120000_expense_bill_tracking.sql
--   supabase/migrations/20260504120000_expense_paper_bill_requested.sql
--   supabase/migrations/20260505180000_expenses_payment_stripe.sql
--   supabase/migrations/20260506120000_expenses_category_balloons.sql
--   supabase/migrations/20260507120000_income_refunds.sql
--   supabase/migrations/20260610140000_accounting_withdrawals.sql
-- =============================================================================

-- >>> BEGIN 20260406000000_expenses.sql

-- Expense tracking for Lanna Bloom internal admin.
-- Private, admin-only. Receipts stored in Supabase Storage (private bucket).
-- Run via: supabase db push  OR  Supabase Dashboard → SQL Editor.

-- =============================================================================
-- 1. EXPENSES table
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.expenses (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  amount          numeric(12,2) NOT NULL CHECK (amount >= 0),
  currency        text NOT NULL DEFAULT 'THB',
  date            date NOT NULL,
  category        text NOT NULL,
  description     text NOT NULL,
  payment_method  text NOT NULL,
  receipt_file_path  text,
  receipt_attached   boolean NOT NULL DEFAULT false,
  created_by      text NOT NULL,
  notes           text,
  linked_order_id text,
  created_at      timestamptz DEFAULT now(),
  updated_at      timestamptz DEFAULT now()
);

-- Category constraint – extend list by adding values here later
ALTER TABLE public.expenses
  DROP CONSTRAINT IF EXISTS expenses_category_check;
ALTER TABLE public.expenses
  ADD CONSTRAINT expenses_category_check
  CHECK (category IN (
    'flowers','packaging','delivery','advertising',
    'supplier_payment','transport','tools_equipment','other'
  ));

-- Payment method constraint
ALTER TABLE public.expenses
  DROP CONSTRAINT IF EXISTS expenses_payment_method_check;
ALTER TABLE public.expenses
  ADD CONSTRAINT expenses_payment_method_check
  CHECK (payment_method IN (
    'cash','bank_transfer','card','qr_payment','other'
  ));

-- =============================================================================
-- 2. INDEXES for common query patterns
-- =============================================================================
CREATE INDEX IF NOT EXISTS expenses_date_idx      ON public.expenses (date DESC);
CREATE INDEX IF NOT EXISTS expenses_category_idx  ON public.expenses (category);
CREATE INDEX IF NOT EXISTS expenses_created_by_idx ON public.expenses (created_by);

-- =============================================================================
-- 3. Row-Level Security – deny all public access; service role bypasses RLS
-- =============================================================================
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;

-- No anon / authenticated policies: only the service-role key (admin backend) can read/write.
-- This table is intentionally not accessible through the anon or auth.users keys.

-- =============================================================================
-- 4. Supabase Storage – private receipts bucket
-- =============================================================================
-- Creates the bucket if it does not already exist.
-- access: private means NO public URL; signed URLs required.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'receipts',
  'receipts',
  false,
  10485760,   -- 10 MB max per file
  ARRAY['image/jpeg','image/png','image/webp','image/heic','application/pdf']
)
ON CONFLICT (id) DO NOTHING;

-- Storage RLS: deny anon access; service-role bypasses storage RLS.
-- No additional policies needed because we generate signed URLs server-side.

-- <<< END 20260406000000_expenses.sql

-- >>> BEGIN 20260406010000_income_records.sql

-- Income records for Lanna Bloom accounting module.
-- Supports both automatic order-based income and manual entries.
-- Run via: supabase db push  OR  Supabase Dashboard → SQL Editor.

-- =============================================================================
-- 1. INCOME_RECORDS table
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.income_records (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Link to order (nullable for manual/legacy/offline entries)
  order_id          text UNIQUE,   -- UNIQUE ensures one income per order (dedup)

  -- How the record was created
  source_mode       text NOT NULL DEFAULT 'manual',
  -- 'auto_order' = created by payment hook, 'manual' = admin entered

  -- What kind of income
  source_type       text NOT NULL DEFAULT 'order',
  -- 'order' | 'legacy_order' | 'offline_sale' | 'adjustment'

  amount            numeric(12,2) NOT NULL CHECK (amount > 0),
  currency          text NOT NULL DEFAULT 'THB',

  payment_method    text NOT NULL,
  -- 'cash' | 'bank_transfer' | 'stripe' | 'qr_payment' | 'other'

  money_location    text NOT NULL,
  -- Where the money landed: 'bank' | 'cash' | 'stripe' | 'other'

  income_status     text NOT NULL DEFAULT 'confirmed',
  -- 'confirmed' | 'pending' | 'cancelled'

  description       text NOT NULL,
  external_reference text,   -- optional: Stripe PI, LINE payment ref, bank slip no.

  -- Receipt / proof of payment
  proof_file_path   text,
  receipt_attached  boolean NOT NULL DEFAULT false,

  notes             text,

  -- Who and when
  created_by        text NOT NULL,
  created_at        timestamptz DEFAULT now(),
  updated_at        timestamptz DEFAULT now(),
  confirmed_at      timestamptz
);

-- =============================================================================
-- 2. Constraints
-- =============================================================================
ALTER TABLE public.income_records
  DROP CONSTRAINT IF EXISTS income_records_source_mode_check;
ALTER TABLE public.income_records
  ADD CONSTRAINT income_records_source_mode_check
  CHECK (source_mode IN ('auto_order', 'manual'));

ALTER TABLE public.income_records
  DROP CONSTRAINT IF EXISTS income_records_source_type_check;
ALTER TABLE public.income_records
  ADD CONSTRAINT income_records_source_type_check
  CHECK (source_type IN ('order', 'legacy_order', 'offline_sale', 'adjustment'));

ALTER TABLE public.income_records
  DROP CONSTRAINT IF EXISTS income_records_income_status_check;
ALTER TABLE public.income_records
  ADD CONSTRAINT income_records_income_status_check
  CHECK (income_status IN ('confirmed', 'pending', 'cancelled'));

-- =============================================================================
-- 3. Indexes
-- =============================================================================
CREATE INDEX IF NOT EXISTS income_records_order_id_idx     ON public.income_records (order_id);
CREATE INDEX IF NOT EXISTS income_records_created_at_idx   ON public.income_records (created_at DESC);
CREATE INDEX IF NOT EXISTS income_records_source_mode_idx  ON public.income_records (source_mode);
CREATE INDEX IF NOT EXISTS income_records_income_status_idx ON public.income_records (income_status);

-- =============================================================================
-- 4. Row-Level Security – admin only via service role
-- =============================================================================
ALTER TABLE public.income_records ENABLE ROW LEVEL SECURITY;
-- No anon/auth.users policies. Service role key bypasses RLS.

-- =============================================================================
-- 5. Supabase Storage – proofs bucket (for income proof files)
-- =============================================================================
-- Reuse the 'receipts' bucket from expenses if already created, OR create 'proofs'.
-- Using a separate 'proofs' bucket keeps income files isolated.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'proofs',
  'proofs',
  false,
  10485760,
  ARRAY['image/jpeg','image/png','image/webp','image/heic','application/pdf']
)
ON CONFLICT (id) DO NOTHING;

-- <<< END 20260406010000_income_records.sql

-- >>> BEGIN 20260406120000_income_processing_fee.sql

-- Processing fee per income row (Stripe/card: fixed 5.3% of gross). Used for net profit in admin accounting.

ALTER TABLE public.income_records
  ADD COLUMN IF NOT EXISTS processing_fee_amount numeric(12,2) NOT NULL DEFAULT 0;

COMMENT ON COLUMN public.income_records.processing_fee_amount IS
  'Payment processing fee (THB). Stripe/card rows: 5.3% of amount; other methods: 0.';

-- Backfill existing rows (Stripe = 5.3% of gross; cancelled rows store 0)
UPDATE public.income_records
SET processing_fee_amount = CASE
  WHEN income_status = 'cancelled' THEN 0
  WHEN payment_method = 'stripe' THEN ROUND((amount * 0.053)::numeric, 2)
  ELSE 0
END
WHERE processing_fee_amount = 0;

-- <<< END 20260406120000_income_processing_fee.sql

-- >>> BEGIN 20260408001000_accounting_transfers.sql

-- Internal accounting transfers (move funds between money locations).
-- Example: Stripe payout (stripe → bank), cash withdrawal (bank → cash).
-- Transfers must NOT affect profit; they only re-allocate balances between locations.

CREATE TABLE IF NOT EXISTS public.accounting_transfers (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  amount         numeric(12,2) NOT NULL CHECK (amount > 0),
  currency       text NOT NULL DEFAULT 'THB',
  transfer_date  date NOT NULL DEFAULT (now()::date),
  from_location  text NOT NULL,
  to_location    text NOT NULL,
  note           text,
  created_by     text NOT NULL,
  created_at     timestamptz DEFAULT now(),
  updated_at     timestamptz DEFAULT now()
);

ALTER TABLE public.accounting_transfers
  DROP CONSTRAINT IF EXISTS accounting_transfers_locations_check;
ALTER TABLE public.accounting_transfers
  ADD CONSTRAINT accounting_transfers_locations_check
  CHECK (
    from_location IN ('bank','cash','stripe','other')
    AND to_location IN ('bank','cash','stripe','other')
    AND from_location <> to_location
  );

CREATE INDEX IF NOT EXISTS accounting_transfers_transfer_date_idx
  ON public.accounting_transfers (transfer_date DESC);

CREATE INDEX IF NOT EXISTS accounting_transfers_created_at_idx
  ON public.accounting_transfers (created_at DESC);

ALTER TABLE public.accounting_transfers ENABLE ROW LEVEL SECURITY;
-- No policies: service role only (admin backend).

-- <<< END 20260408001000_accounting_transfers.sql

-- >>> BEGIN 20260414120000_expense_receipt_images.sql

-- Multiple receipt images per expense (supports 3+ images).

CREATE TABLE IF NOT EXISTS public.expense_receipt_images (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  expense_id uuid NOT NULL REFERENCES public.expenses(id) ON DELETE CASCADE,
  file_path text NOT NULL,
  file_name text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT expense_receipt_images_expense_path_key UNIQUE (expense_id, file_path)
);

CREATE INDEX IF NOT EXISTS expense_receipt_images_expense_id_idx
  ON public.expense_receipt_images (expense_id, created_at DESC);

ALTER TABLE public.expense_receipt_images ENABLE ROW LEVEL SECURITY;

-- Backfill existing single receipt path values into the new table.
INSERT INTO public.expense_receipt_images (expense_id, file_path, file_name)
SELECT
  e.id,
  e.receipt_file_path,
  split_part(e.receipt_file_path, '/', array_length(string_to_array(e.receipt_file_path, '/'), 1))
FROM public.expenses e
WHERE e.receipt_file_path IS NOT NULL
ON CONFLICT (expense_id, file_path) DO NOTHING;

-- <<< END 20260414120000_expense_receipt_images.sql

-- >>> BEGIN 20260430130000_accounting_transfer_payout_metadata.sql

-- Stripe payout / money transfer metadata.
-- Transfers remain neutral: they move money between locations and must not affect revenue or profit.

ALTER TABLE public.accounting_transfers
  ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'received',
  ADD COLUMN IF NOT EXISTS external_reference text,
  ADD COLUMN IF NOT EXISTS bank_received_date date,
  ADD COLUMN IF NOT EXISTS attachment_file_path text,
  ADD COLUMN IF NOT EXISTS attachment_attached boolean NOT NULL DEFAULT false;

ALTER TABLE public.accounting_transfers
  DROP CONSTRAINT IF EXISTS accounting_transfers_status_check;
ALTER TABLE public.accounting_transfers
  ADD CONSTRAINT accounting_transfers_status_check
  CHECK (status IN ('pending', 'received', 'reconciled'));

COMMENT ON COLUMN public.accounting_transfers.status IS
  'Transfer lifecycle. Pending transfers are visible but do not move money-location balances until received/reconciled.';
COMMENT ON COLUMN public.accounting_transfers.external_reference IS
  'External reference such as Stripe payout ID.';
COMMENT ON COLUMN public.accounting_transfers.bank_received_date IS
  'Date the destination bank account received the transfer.';
COMMENT ON COLUMN public.accounting_transfers.attachment_file_path IS
  'Optional proof/screenshot stored in the private proofs bucket.';

CREATE INDEX IF NOT EXISTS accounting_transfers_status_idx
  ON public.accounting_transfers (status);

CREATE INDEX IF NOT EXISTS accounting_transfers_external_reference_idx
  ON public.accounting_transfers (external_reference);

-- <<< END 20260430130000_accounting_transfer_payout_metadata.sql

-- >>> BEGIN 20260502120000_income_paid_date.sql

-- Add a real "paid date" to income records so monthly accounting totals align
-- with expense `date`. Without this, filters use `created_at` (when the row was
-- inserted), which can drift from when the customer actually paid — e.g. a
-- cash sale that happened yesterday but is entered today would show in today's
-- monthly total.
--
-- Backwards-compatible:
--   * Existing rows are backfilled to `created_at::date`.
--   * Default for new rows is `now()::date`, so older insert paths keep working
--     even before they're updated to set `paid_date` explicitly.

ALTER TABLE public.income_records
  ADD COLUMN IF NOT EXISTS paid_date date;

UPDATE public.income_records
   SET paid_date = created_at::date
 WHERE paid_date IS NULL;

ALTER TABLE public.income_records
  ALTER COLUMN paid_date SET NOT NULL,
  ALTER COLUMN paid_date SET DEFAULT (now()::date);

CREATE INDEX IF NOT EXISTS income_records_paid_date_idx
  ON public.income_records (paid_date DESC);

-- <<< END 20260502120000_income_paid_date.sql

-- >>> BEGIN 20260503120000_expense_bill_tracking.sql

-- Dual bill checklist per expense line: (1) proof of payment / transfer to shop,
-- (2) bill from the shop (vendor receipt). For linked orders, one row per order line
-- (e.g. flowers + toys → 4 checkboxes total). Stored as JSONB on expenses.

ALTER TABLE public.expenses
  ADD COLUMN IF NOT EXISTS bill_tracking jsonb NOT NULL DEFAULT '[]'::jsonb;

COMMENT ON COLUMN public.expenses.bill_tracking IS
  'Array of { line_id, label, transfer_to_shop, bill_from_shop, vendor_bill_applicable? }. order:delivery = driver payment only (vendor_bill_applicable false). Else oi:/oj:/default.';

-- <<< END 20260503120000_expense_bill_tracking.sql

-- >>> BEGIN 20260504120000_expense_paper_bill_requested.sql

-- Track when staff generated a vendor "paper bill request" PDF for recovery.

ALTER TABLE public.expenses
  ADD COLUMN IF NOT EXISTS paper_bill_requested_at timestamptz;

COMMENT ON COLUMN public.expenses.paper_bill_requested_at IS
  'Timestamp when a paper bill request PDF was generated (shop/vendor follow-up).';

-- <<< END 20260504120000_expense_paper_bill_requested.sql

-- >>> BEGIN 20260505180000_expenses_payment_stripe.sql

-- Allow expenses paid directly from Stripe balance (before payout).

ALTER TABLE public.expenses
  DROP CONSTRAINT IF EXISTS expenses_payment_method_check;
ALTER TABLE public.expenses
  ADD CONSTRAINT expenses_payment_method_check
  CHECK (payment_method IN (
    'cash','bank_transfer','card','qr_payment','other','stripe'
  ));

-- <<< END 20260505180000_expenses_payment_stripe.sql

-- >>> BEGIN 20260506120000_expenses_category_balloons.sql

-- Balloons sold with bouquets / gifts — COGS bucket with packaging, soft toys, cards.

ALTER TABLE public.expenses
  DROP CONSTRAINT IF EXISTS expenses_category_check;
ALTER TABLE public.expenses
  ADD CONSTRAINT expenses_category_check
  CHECK (category IN (
    'flowers','packaging','delivery','advertising',
    'supplier_payment','transport','tools_equipment','soft_toys','greeting_cards','balloons','other'
  ));

-- <<< END 20260506120000_expenses_category_balloons.sql

-- >>> BEGIN 20260507120000_income_refunds.sql

-- Refunds reduce recognized revenue for a period without altering UNIQUE(order_id) on income_records.
-- One row per Stripe refund (or manual adjustment); keyed by stripe_refund_id when present.

CREATE TABLE IF NOT EXISTS public.income_refunds (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id          text NOT NULL,
  amount            numeric(12,2) NOT NULL CHECK (amount > 0),
  currency          text NOT NULL DEFAULT 'THB',
  refunded_at       date NOT NULL,
  source            text NOT NULL DEFAULT 'stripe',
  stripe_refund_id  text UNIQUE,
  notes             text,
  created_by        text,
  created_at        timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS income_refunds_order_id_idx
  ON public.income_refunds (order_id);
CREATE INDEX IF NOT EXISTS income_refunds_refunded_at_idx
  ON public.income_refunds (refunded_at DESC);

ALTER TABLE public.income_refunds
  DROP CONSTRAINT IF EXISTS income_refunds_source_check;
ALTER TABLE public.income_refunds
  ADD CONSTRAINT income_refunds_source_check
  CHECK (source IN ('stripe', 'manual'));

ALTER TABLE public.income_refunds ENABLE ROW LEVEL SECURITY;

-- <<< END 20260507120000_income_refunds.sql

-- >>> BEGIN 20260610140000_accounting_withdrawals.sql

-- Owner / personal withdrawals: money leaves the business ledger for personal use.
-- Not income, not expense, not inter-bucket transfer. Reduces location balance only.

CREATE TABLE IF NOT EXISTS public.accounting_withdrawals (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  amount            numeric(12,2) NOT NULL CHECK (amount > 0),
  currency          text NOT NULL DEFAULT 'THB',
  withdrawal_date   date NOT NULL DEFAULT (now()::date),
  from_location     text NOT NULL,
  purpose           text NOT NULL,
  notes             text,
  status            text NOT NULL DEFAULT 'confirmed',
  proof_file_path   text,
  proof_attached    boolean NOT NULL DEFAULT false,
  created_by        text NOT NULL,
  created_at        timestamptz DEFAULT now(),
  updated_at        timestamptz DEFAULT now()
);

ALTER TABLE public.accounting_withdrawals
  ADD CONSTRAINT accounting_withdrawals_from_location_check
  CHECK (from_location IN ('bank', 'cash', 'stripe', 'other'));

ALTER TABLE public.accounting_withdrawals
  ADD CONSTRAINT accounting_withdrawals_status_check
  CHECK (status IN ('pending', 'confirmed'));

CREATE INDEX IF NOT EXISTS accounting_withdrawals_withdrawal_date_idx
  ON public.accounting_withdrawals (withdrawal_date DESC);

CREATE INDEX IF NOT EXISTS accounting_withdrawals_from_location_idx
  ON public.accounting_withdrawals (from_location);

CREATE INDEX IF NOT EXISTS accounting_withdrawals_created_at_idx
  ON public.accounting_withdrawals (created_at DESC);

ALTER TABLE public.accounting_withdrawals ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.accounting_withdrawals FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.accounting_withdrawals TO service_role;

-- <<< END 20260610140000_accounting_withdrawals.sql

