-- =============================================================================
-- Catalog tables, CMS foundation, storage bucket, pricing_type
-- Generated by: npm run db:bootstrap:assemble
-- Do not edit by hand — change scripts/db-bootstrap-manifest.ts and re-assemble.
-- =============================================================================
-- Source migrations:
--   supabase/migrations/20260526120000_catalog_tables.sql
--   supabase/migrations/20260526120001_catalog_storage_bucket.sql
--   supabase/migrations/20260526123000_catalog_cms_foundation.sql
--   supabase/migrations/20260527120000_catalog_pricing_type.sql
-- =============================================================================

-- >>> BEGIN 20260526120000_catalog_tables.sql

-- Phase 1: Supabase catalog schema (mirrors Sanity bouquet / product / partner / siteSettings).
-- Storefront still reads Sanity; import and cutover in later phases.
-- Access: service role only (RLS enabled, no anon/authenticated policies).

-- =============================================================================
-- 1. Partners
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.catalog_partners (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  legacy_sanity_id    text UNIQUE,
  shop_name           text NOT NULL,
  contact_name        text NOT NULL,
  phone_number        text NOT NULL,
  line_or_whatsapp    text,
  shop_address        text,
  shop_bio_en         text,
  shop_bio_ru         text,
  portrait            jsonb,
  city                text NOT NULL DEFAULT 'Chiang Mai',
  status              text NOT NULL DEFAULT 'pending_review'
    CHECK (status IN ('pending_review', 'approved', 'disabled')),
  supabase_user_id    uuid UNIQUE REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS catalog_partners_legacy_sanity_id_idx
  ON public.catalog_partners (legacy_sanity_id)
  WHERE legacy_sanity_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS catalog_partners_supabase_user_id_idx
  ON public.catalog_partners (supabase_user_id)
  WHERE supabase_user_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS catalog_partners_status_idx
  ON public.catalog_partners (status);

-- =============================================================================
-- 2. Bouquets (flowers)
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.catalog_bouquets (
  id                              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  legacy_sanity_id                text UNIQUE,
  partner_id                      uuid REFERENCES public.catalog_partners(id) ON DELETE SET NULL,
  slug_en                         text NOT NULL,
  slug_ru                         text,
  name_en                         text NOT NULL,
  name_ru                         text NOT NULL DEFAULT '',
  description_en                  text NOT NULL DEFAULT '',
  description_ru                  text NOT NULL DEFAULT '',
  composition_en                  text NOT NULL DEFAULT '',
  composition_ru                  text NOT NULL DEFAULT '',
  product_kind                    text NOT NULL DEFAULT 'legacy'
    CHECK (product_kind IN (
      'legacy', 'single_stem_count', 'fixed_bouquet', 'customizable_bouquet'
    )),
  -- Mirrors Sanity option arrays; loaders map to BouquetSellableOption[].
  pricing                         jsonb NOT NULL DEFAULT '{"sizes":[]}'::jsonb,
  status                          text NOT NULL DEFAULT 'approved'
    CHECK (status IN ('pending_review', 'approved', 'rejected')),
  featured_popular                boolean NOT NULL DEFAULT false,
  discount_percent                smallint
    CHECK (discount_percent IS NULL OR (discount_percent >= 1 AND discount_percent <= 90)),
  delivery_options                text[] NOT NULL DEFAULT '{}',
  excluded_delivery_destinations  text[] NOT NULL DEFAULT '{}',
  presentation_formats            text[] NOT NULL DEFAULT '{}',
  colors                          text[] NOT NULL DEFAULT '{}',
  flower_types                    text[] NOT NULL DEFAULT '{}',
  occasion                        text[] NOT NULL DEFAULT '{}',
  images                          jsonb NOT NULL DEFAULT '[]'::jsonb,
  source                          text,
  created_by                      text,
  approved_by                     text,
  approved_at                     timestamptz,
  created_at                      timestamptz NOT NULL DEFAULT now(),
  updated_at                      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT catalog_bouquets_slug_en_key UNIQUE (slug_en)
);

CREATE INDEX IF NOT EXISTS catalog_bouquets_legacy_sanity_id_idx
  ON public.catalog_bouquets (legacy_sanity_id)
  WHERE legacy_sanity_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS catalog_bouquets_partner_id_idx
  ON public.catalog_bouquets (partner_id);

CREATE INDEX IF NOT EXISTS catalog_bouquets_status_idx
  ON public.catalog_bouquets (status);

CREATE INDEX IF NOT EXISTS catalog_bouquets_featured_popular_idx
  ON public.catalog_bouquets (featured_popular)
  WHERE featured_popular = true;

CREATE INDEX IF NOT EXISTS catalog_bouquets_slug_ru_idx
  ON public.catalog_bouquets (slug_ru)
  WHERE slug_ru IS NOT NULL;

-- =============================================================================
-- 3. Products (non-flower)
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.catalog_products (
  id                              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  legacy_sanity_id                text UNIQUE,
  partner_id                      uuid NOT NULL REFERENCES public.catalog_partners(id) ON DELETE RESTRICT,
  slug_en                         text NOT NULL,
  slug_ru                         text,
  name_en                         text NOT NULL,
  name_ru                         text NOT NULL DEFAULT '',
  description_en                  text NOT NULL DEFAULT '',
  description_ru                  text NOT NULL DEFAULT '',
  category                        text NOT NULL,
  price                           numeric(12,2) NOT NULL CHECK (price >= 0),
  cost                            numeric(12,2) CHECK (cost IS NULL OR cost >= 0),
  commission_percent              numeric(6,2) CHECK (
    commission_percent IS NULL OR (commission_percent >= 0 AND commission_percent <= 500)
  ),
  moderation_status               text NOT NULL DEFAULT 'submitted'
    CHECK (moderation_status IN ('submitted', 'live', 'needs_changes', 'rejected')),
  admin_note                      text,
  discount_percent                smallint
    CHECK (discount_percent IS NULL OR (discount_percent >= 1 AND discount_percent <= 90)),
  excluded_delivery_destinations  text[] NOT NULL DEFAULT '{}',
  images                          jsonb NOT NULL DEFAULT '[]'::jsonb,
  structured_attributes           jsonb NOT NULL DEFAULT '{}'::jsonb,
  custom_attributes               jsonb NOT NULL DEFAULT '[]'::jsonb,
  admin_overrides                 jsonb,
  admin_change_summary            text,
  admin_last_edited_at            timestamptz,
  admin_last_edited_by            text,
  created_at                      timestamptz NOT NULL DEFAULT now(),
  updated_at                      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT catalog_products_slug_en_key UNIQUE (slug_en),
  CONSTRAINT catalog_products_category_check CHECK (category IN (
    'balloons', 'plushy_toys', 'gifts', 'money_flowers', 'handmade_floral',
    'food_sweets', 'wellness', 'home_lifestyle', 'stationery', 'baby_family',
    'fashion', 'seasonal', 'other'
  ))
);

CREATE INDEX IF NOT EXISTS catalog_products_legacy_sanity_id_idx
  ON public.catalog_products (legacy_sanity_id)
  WHERE legacy_sanity_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS catalog_products_partner_id_idx
  ON public.catalog_products (partner_id);

CREATE INDEX IF NOT EXISTS catalog_products_moderation_status_idx
  ON public.catalog_products (moderation_status);

CREATE INDEX IF NOT EXISTS catalog_products_category_idx
  ON public.catalog_products (category);

CREATE INDEX IF NOT EXISTS catalog_products_slug_ru_idx
  ON public.catalog_products (slug_ru)
  WHERE slug_ru IS NOT NULL;

-- =============================================================================
-- 4. Homepage media (siteSettings singleton)
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.catalog_site_settings (
  id                    text PRIMARY KEY DEFAULT 'default'
    CHECK (id = 'default'),
  hero_image            jsonb,
  hero_carousel_images  jsonb NOT NULL DEFAULT '[]'::jsonb,
  updated_at            timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.catalog_site_settings (id)
VALUES ('default')
ON CONFLICT (id) DO NOTHING;

-- =============================================================================
-- 5. Global slug registry (per locale)
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.catalog_slug_registry (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug          text NOT NULL,
  locale        text NOT NULL CHECK (locale IN ('en', 'ru')),
  entity_type   text NOT NULL CHECK (entity_type IN ('bouquet', 'product')),
  entity_id     uuid NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT catalog_slug_registry_slug_locale_key UNIQUE (slug, locale)
);

CREATE INDEX IF NOT EXISTS catalog_slug_registry_entity_idx
  ON public.catalog_slug_registry (entity_type, entity_id);

-- =============================================================================
-- 6. Row-Level Security — admin backend (service role) only
-- =============================================================================
ALTER TABLE public.catalog_partners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.catalog_bouquets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.catalog_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.catalog_site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.catalog_slug_registry ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.catalog_partners FROM anon, authenticated;
REVOKE ALL ON TABLE public.catalog_bouquets FROM anon, authenticated;
REVOKE ALL ON TABLE public.catalog_products FROM anon, authenticated;
REVOKE ALL ON TABLE public.catalog_site_settings FROM anon, authenticated;
REVOKE ALL ON TABLE public.catalog_slug_registry FROM anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.catalog_partners TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.catalog_bouquets TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.catalog_products TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.catalog_site_settings TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.catalog_slug_registry TO service_role;

-- <<< END 20260526120000_catalog_tables.sql

-- >>> BEGIN 20260526120001_catalog_storage_bucket.sql

-- Public catalog images bucket (product/bouquet/partner portraits, homepage hero).
-- Uploads: server-side via service role only (see lib/catalogWrite.ts, Phase 2+).

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'catalog',
  'catalog',
  true,
  10485760,
  ARRAY['image/jpeg', 'image/png', 'image/webp']
)
ON CONFLICT (id) DO NOTHING;

-- Public read: bucket is public=true (anonymous GET via public URL).
-- No INSERT/UPDATE/DELETE policies for anon or authenticated — uploads use service role.

-- <<< END 20260526120001_catalog_storage_bucket.sql

-- >>> BEGIN 20260526123000_catalog_cms_foundation.sql

-- Product CMS foundation: revisions, normalized images, collections, and audit.
-- Additive only. Storefront reads continue to use catalog_bouquets/catalog_products as
-- the published read model until the unified CMS is fully wired.

-- =============================================================================
-- 1. Draft / review / publish revisions
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.catalog_product_revisions (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  entity_type           text NOT NULL CHECK (entity_type IN ('bouquet', 'product')),
  entity_id             uuid,
  base_revision_id      uuid REFERENCES public.catalog_product_revisions(id) ON DELETE SET NULL,
  source                text NOT NULL DEFAULT 'admin_manual'
    CHECK (source IN ('admin_manual', 'admin_ai', 'partner_edit', 'import')),
  status                text NOT NULL DEFAULT 'draft'
    CHECK (status IN (
      'draft', 'pending_review', 'approved', 'rejected', 'needs_changes',
      'published', 'archived'
    )),
  payload               jsonb NOT NULL DEFAULT '{}'::jsonb,
  seo_title_en          text,
  seo_title_ru          text,
  seo_description_en    text,
  seo_description_ru    text,
  seo_keywords          text[] NOT NULL DEFAULT '{}',
  og_image_path         text,
  moderation_note       text,
  rejection_reason      text,
  created_by            text,
  edited_by             text,
  approved_by           text,
  published_by          text,
  approved_at           timestamptz,
  published_at          timestamptz,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT catalog_product_revisions_existing_entity_check
    CHECK (entity_id IS NOT NULL OR status IN ('draft', 'pending_review', 'rejected', 'needs_changes', 'archived'))
);

CREATE INDEX IF NOT EXISTS catalog_product_revisions_entity_idx
  ON public.catalog_product_revisions (entity_type, entity_id);

CREATE INDEX IF NOT EXISTS catalog_product_revisions_status_idx
  ON public.catalog_product_revisions (status, updated_at DESC);

CREATE INDEX IF NOT EXISTS catalog_product_revisions_source_idx
  ON public.catalog_product_revisions (source);

-- =============================================================================
-- 2. Normalized product images
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.catalog_product_images (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  entity_type           text NOT NULL CHECK (entity_type IN ('bouquet', 'product')),
  entity_id             uuid,
  revision_id           uuid REFERENCES public.catalog_product_revisions(id) ON DELETE SET NULL,
  storage_path          text NOT NULL CHECK (length(btrim(storage_path)) > 0),
  public_url            text,
  source_type           text NOT NULL DEFAULT 'uploaded'
    CHECK (source_type IN ('uploaded', 'ai_generated', 'migrated_from_sanity')),
  original_image_id     uuid REFERENCES public.catalog_product_images(id) ON DELETE SET NULL,
  alt_en                text,
  alt_ru                text,
  is_primary            boolean NOT NULL DEFAULT false,
  sort_order            integer NOT NULL DEFAULT 0,
  metadata              jsonb NOT NULL DEFAULT '{}'::jsonb,
  deleted_at            timestamptz,
  created_by            text,
  updated_by            text,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT catalog_product_images_entity_or_revision_check
    CHECK (entity_id IS NOT NULL OR revision_id IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS catalog_product_images_entity_idx
  ON public.catalog_product_images (entity_type, entity_id, sort_order)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS catalog_product_images_revision_idx
  ON public.catalog_product_images (revision_id, sort_order)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS catalog_product_images_storage_path_idx
  ON public.catalog_product_images (storage_path);

CREATE UNIQUE INDEX IF NOT EXISTS catalog_product_images_one_primary_live_idx
  ON public.catalog_product_images (entity_type, entity_id)
  WHERE revision_id IS NULL AND deleted_at IS NULL AND is_primary = true;

CREATE UNIQUE INDEX IF NOT EXISTS catalog_product_images_one_primary_revision_idx
  ON public.catalog_product_images (revision_id)
  WHERE revision_id IS NOT NULL AND deleted_at IS NULL AND is_primary = true;

-- Backfill current inline image metadata into the normalized table for admin use.
INSERT INTO public.catalog_product_images (
  entity_type,
  entity_id,
  storage_path,
  public_url,
  source_type,
  alt_en,
  is_primary,
  sort_order,
  metadata,
  created_at,
  updated_at
)
SELECT
  'bouquet',
  image_row.entity_id,
  image_row.storage_path,
  image_row.public_url,
  'migrated_from_sanity',
  image_row.alt,
  image_row.primary_rank = 1,
  image_row.sort_order,
  image_row.metadata,
  image_row.source_created_at,
  now()
FROM (
  SELECT
    bouquet.id AS entity_id,
    bouquet.created_at AS source_created_at,
    image.value->>'storage_path' AS storage_path,
    image.value->>'public_url' AS public_url,
    image.value->>'alt' AS alt,
    COALESCE((image.value->>'sort_order')::integer, image.ordinality - 1) AS sort_order,
    jsonb_strip_nulls(jsonb_build_object(
      'format', image.value->>'format',
      'backfilled_from', 'catalog_bouquets.images'
    )) AS metadata,
    row_number() OVER (
      PARTITION BY bouquet.id
      ORDER BY
        CASE WHEN COALESCE((image.value->>'is_primary')::boolean, false) THEN 0 ELSE 1 END,
        COALESCE((image.value->>'sort_order')::integer, image.ordinality - 1),
        image.ordinality
    ) AS primary_rank
  FROM public.catalog_bouquets AS bouquet
  CROSS JOIN LATERAL jsonb_array_elements(bouquet.images) WITH ORDINALITY AS image(value, ordinality)
  WHERE COALESCE(image.value->>'storage_path', '') <> ''
) AS image_row
WHERE image_row.storage_path <> ''
  AND NOT EXISTS (
    SELECT 1
    FROM public.catalog_product_images existing
    WHERE existing.entity_type = 'bouquet'
      AND existing.entity_id = image_row.entity_id
      AND existing.revision_id IS NULL
      AND existing.storage_path = image_row.storage_path
  );

INSERT INTO public.catalog_product_images (
  entity_type,
  entity_id,
  storage_path,
  public_url,
  source_type,
  alt_en,
  is_primary,
  sort_order,
  metadata,
  created_at,
  updated_at
)
SELECT
  'product',
  image_row.entity_id,
  image_row.storage_path,
  image_row.public_url,
  'migrated_from_sanity',
  image_row.alt,
  image_row.primary_rank = 1,
  image_row.sort_order,
  image_row.metadata,
  image_row.source_created_at,
  now()
FROM (
  SELECT
    product.id AS entity_id,
    product.created_at AS source_created_at,
    image.value->>'storage_path' AS storage_path,
    image.value->>'public_url' AS public_url,
    image.value->>'alt' AS alt,
    COALESCE((image.value->>'sort_order')::integer, image.ordinality - 1) AS sort_order,
    jsonb_strip_nulls(jsonb_build_object(
      'format', image.value->>'format',
      'backfilled_from', 'catalog_products.images'
    )) AS metadata,
    row_number() OVER (
      PARTITION BY product.id
      ORDER BY
        CASE WHEN COALESCE((image.value->>'is_primary')::boolean, false) THEN 0 ELSE 1 END,
        COALESCE((image.value->>'sort_order')::integer, image.ordinality - 1),
        image.ordinality
    ) AS primary_rank
  FROM public.catalog_products AS product
  CROSS JOIN LATERAL jsonb_array_elements(product.images) WITH ORDINALITY AS image(value, ordinality)
  WHERE COALESCE(image.value->>'storage_path', '') <> ''
) AS image_row
WHERE image_row.storage_path <> ''
  AND NOT EXISTS (
    SELECT 1
    FROM public.catalog_product_images existing
    WHERE existing.entity_type = 'product'
      AND existing.entity_id = image_row.entity_id
      AND existing.revision_id IS NULL
      AND existing.storage_path = image_row.storage_path
  );

-- =============================================================================
-- 3. Merchandising collections and placements
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.catalog_collections (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug                  text NOT NULL UNIQUE,
  placement             text NOT NULL DEFAULT 'custom'
    CHECK (placement IN (
      'homepage_popular', 'bouquet_add_ons', 'bouquet_recommendations',
      'product_recommendations', 'plushy_toys', 'balloons',
      'collection_add_ons', 'custom'
    )),
  title_en              text NOT NULL,
  title_th              text NOT NULL DEFAULT '',
  description_en        text NOT NULL DEFAULT '',
  description_ru        text NOT NULL DEFAULT '',
  seo_title_en          text,
  seo_title_ru          text,
  seo_description_en    text,
  seo_description_ru    text,
  fallback_mode         text NOT NULL DEFAULT 'automatic'
    CHECK (fallback_mode IN ('automatic', 'empty', 'category', 'popular')),
  is_active             boolean NOT NULL DEFAULT true,
  starts_at             timestamptz,
  ends_at               timestamptz,
  sort_order            integer NOT NULL DEFAULT 0,
  created_by            text,
  updated_by            text,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT catalog_collections_slug_not_blank CHECK (length(btrim(slug)) > 0),
  CONSTRAINT catalog_collections_schedule_check CHECK (ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at)
);

CREATE INDEX IF NOT EXISTS catalog_collections_placement_idx
  ON public.catalog_collections (placement, is_active, sort_order);

CREATE INDEX IF NOT EXISTS catalog_collections_active_window_idx
  ON public.catalog_collections (is_active, starts_at, ends_at);

CREATE TABLE IF NOT EXISTS public.catalog_collection_items (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  collection_id         uuid NOT NULL REFERENCES public.catalog_collections(id) ON DELETE CASCADE,
  entity_type           text NOT NULL CHECK (entity_type IN ('bouquet', 'product')),
  entity_id             uuid NOT NULL,
  sort_order            integer NOT NULL DEFAULT 0,
  label_en              text,
  label_th              text,
  is_active             boolean NOT NULL DEFAULT true,
  metadata              jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT catalog_collection_items_unique_entity
    UNIQUE (collection_id, entity_type, entity_id)
);

CREATE INDEX IF NOT EXISTS catalog_collection_items_collection_idx
  ON public.catalog_collection_items (collection_id, is_active, sort_order);

CREATE INDEX IF NOT EXISTS catalog_collection_items_entity_idx
  ON public.catalog_collection_items (entity_type, entity_id);

-- =============================================================================
-- 4. Audit events
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.catalog_audit_events (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  entity_type           text CHECK (entity_type IN ('bouquet', 'product', 'collection', 'image', 'partner')),
  entity_id             uuid,
  revision_id           uuid REFERENCES public.catalog_product_revisions(id) ON DELETE SET NULL,
  action                text NOT NULL,
  actor                 text,
  before_summary        jsonb,
  after_summary         jsonb,
  metadata              jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at            timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT catalog_audit_events_action_not_blank CHECK (length(btrim(action)) > 0)
);

CREATE INDEX IF NOT EXISTS catalog_audit_events_entity_idx
  ON public.catalog_audit_events (entity_type, entity_id, created_at DESC);

CREATE INDEX IF NOT EXISTS catalog_audit_events_revision_idx
  ON public.catalog_audit_events (revision_id, created_at DESC);

-- =============================================================================
-- 5. Row-Level Security — admin backend (service role) only
-- =============================================================================
ALTER TABLE public.catalog_product_revisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.catalog_product_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.catalog_collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.catalog_collection_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.catalog_audit_events ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.catalog_product_revisions FROM anon, authenticated;
REVOKE ALL ON TABLE public.catalog_product_images FROM anon, authenticated;
REVOKE ALL ON TABLE public.catalog_collections FROM anon, authenticated;
REVOKE ALL ON TABLE public.catalog_collection_items FROM anon, authenticated;
REVOKE ALL ON TABLE public.catalog_audit_events FROM anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.catalog_product_revisions TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.catalog_product_images TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.catalog_collections TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.catalog_collection_items TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.catalog_audit_events TO service_role;

-- <<< END 20260526123000_catalog_cms_foundation.sql

-- >>> BEGIN 20260527120000_catalog_pricing_type.sql

-- Replace product_kind with pricing_type (single_price | size_based | stem_count).

ALTER TABLE public.catalog_bouquets
  ADD COLUMN IF NOT EXISTS pricing_type text;

-- Backfill pricing_type from product_kind + pricing shape
UPDATE public.catalog_bouquets
SET pricing_type = CASE
  WHEN product_kind = 'single_stem_count' THEN 'stem_count'
  WHEN product_kind = 'fixed_bouquet' THEN 'size_based'
  WHEN product_kind = 'customizable_bouquet' THEN 'single_price'
  WHEN product_kind = 'legacy' AND (
    SELECT COUNT(*)::int
    FROM jsonb_array_elements(COALESCE(pricing -> 'sizes', '[]'::jsonb)) el
    WHERE COALESCE((el ->> 'price')::numeric, 0) > 0
      AND COALESCE((el ->> 'availability')::text, 'true') IS DISTINCT FROM 'false'
  ) >= 2 THEN 'size_based'
  ELSE 'single_price'
END
WHERE pricing_type IS NULL;

UPDATE public.catalog_bouquets
SET pricing_type = 'single_price'
WHERE pricing_type IS NULL;

ALTER TABLE public.catalog_bouquets
  ALTER COLUMN pricing_type SET DEFAULT 'single_price',
  ALTER COLUMN pricing_type SET NOT NULL;

ALTER TABLE public.catalog_bouquets
  DROP CONSTRAINT IF EXISTS catalog_bouquets_product_kind_check;

ALTER TABLE public.catalog_bouquets
  ADD CONSTRAINT catalog_bouquets_pricing_type_check
  CHECK (pricing_type IN ('single_price', 'size_based', 'stem_count'));

-- Drop legacy column after backfill (pricing JSON migration via scripts/migrate-catalog-pricing.ts)
ALTER TABLE public.catalog_bouquets
  DROP COLUMN IF EXISTS product_kind;

COMMENT ON COLUMN public.catalog_bouquets.pricing_type IS
  'single_price | size_based (S/M/L/XL) | stem_count (rose tiers)';

-- <<< END 20260527120000_catalog_pricing_type.sql


-- >>> Russia / project tail SQL

-- EKB Flowers (Russia) defaults — not in Thailand incremental history
ALTER TABLE public.catalog_partners
  ALTER COLUMN city SET DEFAULT 'Yekaterinburg';

-- Allow Russian locale slugs when importing RU storefront content
ALTER TABLE public.catalog_slug_registry
  DROP CONSTRAINT IF EXISTS catalog_slug_registry_locale_check;
ALTER TABLE public.catalog_slug_registry
  ADD CONSTRAINT catalog_slug_registry_locale_check
  CHECK (locale IN ('en', 'ru'));


