-- =============================================================================
-- RLS catch-all, service_role grants, optional app_settings / order_photos
-- Generated by: npm run db:bootstrap:assemble
-- Do not edit by hand — change scripts/db-bootstrap-manifest.ts and re-assemble.
-- =============================================================================
-- Source migrations:
--   supabase/migrations/20260508123000_rls_private_checkout_drafts_and_email_tables.sql
--   supabase/migrations/20260610120000_harden_public_schema_rls.sql
--   supabase/migrations/20260610130000_rls_app_settings_order_photos.sql
-- =============================================================================

-- >>> BEGIN 20260508123000_rls_private_checkout_drafts_and_email_tables.sql

-- Ensure sensitive operational tables are protected by RLS.
-- These tables are intended for service-role backend access only (no anon/auth policies).

ALTER TABLE IF EXISTS public.checkout_drafts ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.email_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.email_outbox ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.customer_reminders ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.reminder_email_logs ENABLE ROW LEVEL SECURITY;

-- Defense-in-depth: revoke accidental broad grants for public roles.
REVOKE ALL ON TABLE public.checkout_drafts FROM anon, authenticated;
REVOKE ALL ON TABLE public.email_templates FROM anon, authenticated;
REVOKE ALL ON TABLE public.email_outbox FROM anon, authenticated;
REVOKE ALL ON TABLE public.customer_reminders FROM anon, authenticated;
REVOKE ALL ON TABLE public.reminder_email_logs FROM anon, authenticated;

-- <<< END 20260508123000_rls_private_checkout_drafts_and_email_tables.sql

-- >>> BEGIN 20260610120000_harden_public_schema_rls.sql

-- Harden public schema: enable RLS on every table that lacks it.
-- Fixes Supabase Security Advisor "rls_disabled_in_public" (critical).
--
-- Safe to re-run: ENABLE ROW LEVEL SECURITY is idempotent; REVOKE/GRANT are idempotent.
-- Service role bypasses RLS. Tables with intentional anon policies are unchanged.

-- -----------------------------------------------------------------------------
-- 1. Catch-all: any public table still missing RLS
-- -----------------------------------------------------------------------------
DO $$
DECLARE
  r RECORD;
BEGIN
  FOR r IN
    SELECT c.relname AS tablename
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relkind = 'r'
      AND NOT c.relrowsecurity
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', r.tablename);
    RAISE NOTICE 'Enabled RLS on public.%', r.tablename;
  END LOOP;
END $$;

-- -----------------------------------------------------------------------------
-- 2. Explicit backend-only tables (defense in depth: revoke anon/auth, grant service_role)
-- -----------------------------------------------------------------------------
DO $$
DECLARE
  t text;
  tables text[] := ARRAY[
    'checkout_drafts',
    'email_templates',
    'email_outbox',
    'customer_reminders',
    'reminder_email_logs',
    'admin_users',
    'audit_logs',
    'stripe_events',
    'line_order_drafts',
    'line_integration_events',
    'line_agent_payment_notifications',
    'order_notification_sent',
    'expenses',
    'income_records',
    'accounting_transfers',
    'expense_receipt_images',
    'welcome_codes',
    'income_refunds',
    'supplier_order_requests',
    'supplier_order_request_events',
    'catalog_partners',
    'catalog_bouquets',
    'catalog_products',
    'catalog_site_settings',
    'catalog_slug_registry',
    'catalog_product_revisions',
    'catalog_product_images',
    'catalog_collections',
    'catalog_collection_items',
    'catalog_audit_events',
    'drivers',
    'driver_invites',
    'app_settings'
  ];
BEGIN
  FOREACH t IN ARRAY tables
  LOOP
    IF to_regclass('public.' || t) IS NOT NULL THEN
      EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
      EXECUTE format('REVOKE ALL ON TABLE public.%I FROM anon, authenticated', t);
      EXECUTE format(
        'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.%I TO service_role',
        t
      );
    END IF;
  END LOOP;
END $$;

-- -----------------------------------------------------------------------------
-- 3. Order tables: RLS + token policies (re-assert if migration order was partial)
-- -----------------------------------------------------------------------------
ALTER TABLE IF EXISTS public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.order_status_history ENABLE ROW LEVEL SECURITY;

-- <<< END 20260610120000_harden_public_schema_rls.sql

-- >>> BEGIN 20260610130000_rls_app_settings_order_photos.sql

-- RLS for manually created tables: app_settings, order_photos
--
-- app_settings: internal config — service role only (never public Data API).
-- order_photos: customers may view their own order's photos, but only with a
-- valid order public_token (same pattern as orders / order_items).

-- -----------------------------------------------------------------------------
-- app_settings — admin/backend only
-- -----------------------------------------------------------------------------
DO $$
BEGIN
  IF to_regclass('public.app_settings') IS NOT NULL THEN
    ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;
    REVOKE ALL ON TABLE public.app_settings FROM anon, authenticated;
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.app_settings TO service_role;
  END IF;
END $$;

-- -----------------------------------------------------------------------------
-- order_photos — token-scoped customer read; writes via service role only
-- Assumes order_photos.order_id matches orders.order_id (text).
-- -----------------------------------------------------------------------------
DO $$
BEGIN
  IF to_regclass('public.order_photos') IS NOT NULL THEN
    ALTER TABLE public.order_photos ENABLE ROW LEVEL SECURITY;

    DROP POLICY IF EXISTS "order_photos_token_scoped_read" ON public.order_photos;
    CREATE POLICY "order_photos_token_scoped_read"
      ON public.order_photos
      FOR SELECT
      TO anon, authenticated
      USING (
        EXISTS (
          SELECT 1
          FROM public.orders o
          WHERE o.order_id = order_photos.order_id
            AND o.public_token IS NOT NULL
            AND o.public_token = public.request_order_token()
        )
      );

    REVOKE INSERT, UPDATE, DELETE ON TABLE public.order_photos FROM anon, authenticated;
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.order_photos TO service_role;
  END IF;
END $$;

-- <<< END 20260610130000_rls_app_settings_order_photos.sql

