#!/usr/bin/env npx tsx
/**
 * Assemble db/bootstrap/*.sql from curated supabase/migrations subsets.
 * Idempotent: safe to re-run; overwrites generated bootstrap files.
 */

import fs from 'node:fs';
import path from 'node:path';
import {
  BOOTSTRAP_GROUPS,
  BOOTSTRAP_OUTPUT_DIR,
  LEGACY_MIGRATIONS_DIR,
  SKIPPED_MIGRATIONS,
  allBootstrapSourceFiles,
} from './db-bootstrap-manifest';

function banner(title: string, sources: string[]): string {
  const lines = [
    '-- =============================================================================',
    `-- ${title}`,
    '-- Generated by: npm run db:bootstrap:assemble',
    '-- Do not edit by hand — change scripts/db-bootstrap-manifest.ts and re-assemble.',
    '-- =============================================================================',
    '-- Source migrations:',
    ...sources.map((f) => `--   supabase/migrations/${f}`),
    '-- =============================================================================',
    '',
  ];
  return lines.join('\n');
}

function validateManifest(): void {
  const legacyFiles = new Set(
    fs.readdirSync(LEGACY_MIGRATIONS_DIR).filter((f) => f.endsWith('.sql')),
  );
  const used = new Set(allBootstrapSourceFiles());
  const skipped = new Set(SKIPPED_MIGRATIONS.map((s) => s.file));

  for (const file of used) {
    if (!legacyFiles.has(file)) {
      throw new Error(`Bootstrap references missing migration: ${file}`);
    }
  }

  const unused = [...legacyFiles].filter((f) => !used.has(f) && !skipped.has(f));
  if (unused.length > 0) {
    console.warn(
      `[db:bootstrap:assemble] ${unused.length} legacy migration(s) not in bootstrap or skip list:`,
    );
    for (const f of unused.sort()) {
      console.warn(`  - ${f}`);
    }
    console.warn('Add to BOOTSTRAP_GROUPS or SKIPPED_MIGRATIONS in db-bootstrap-manifest.ts');
  }
}

function assemble(): void {
  validateManifest();
  fs.mkdirSync(BOOTSTRAP_OUTPUT_DIR, { recursive: true });

  const generated: string[] = [];

  for (const group of BOOTSTRAP_GROUPS) {
    const outName = `${group.order}_${group.slug}.sql`;
    const outPath = path.join(BOOTSTRAP_OUTPUT_DIR, outName);
    const parts: string[] = [banner(group.title, group.migrations)];

    for (const file of group.migrations) {
      const src = path.join(LEGACY_MIGRATIONS_DIR, file);
      parts.push(`-- >>> BEGIN ${file}\n`);
      parts.push(fs.readFileSync(src, 'utf8').trimEnd());
      parts.push(`\n-- <<< END ${file}\n`);
    }

    if (group.tailSql?.trim()) {
      parts.push('\n-- >>> Russia / project tail SQL\n');
      parts.push(group.tailSql.trimEnd());
      parts.push('\n');
    }

    fs.writeFileSync(outPath, parts.join('\n') + '\n', 'utf8');
    generated.push(outName);
    console.log(`Wrote ${path.relative(process.cwd(), outPath)}`);
  }

  const readme = `# Database bootstrap (generated)

**7 files** replace **68** incremental \`supabase/migrations/\` on a **fresh** Postgres database.

## Apply

\`\`\`bash
# Supabase (Vercel integration) or local
export POSTGRES_URL="postgres://..."
npm run db:bootstrap:apply

# VPS Docker
export DATABASE_URL="postgresql://flower:SECRET@127.0.0.1:5432/flower_ru"
npm run db:bootstrap:apply
\`\`\`

Or paste files in order into Supabase SQL Editor.

## Files (run in order)

${generated.map((f) => `- \`${f}\``).join('\n')}

## Regenerate

After changing \`scripts/db-bootstrap-manifest.ts\`:

\`\`\`bash
npm run db:bootstrap:assemble
\`\`\`

See [docs/DATABASE_BOOTSTRAP.md](../docs/DATABASE_BOOTSTRAP.md) for full rationale.
`;

  fs.writeFileSync(path.join(BOOTSTRAP_OUTPUT_DIR, 'README.md'), readme, 'utf8');
  console.log(`\nDone: ${generated.length} bootstrap files (${allBootstrapSourceFiles().length} legacy sources, ${SKIPPED_MIGRATIONS.length} skipped).`);
}

assemble();
